// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/fee": {
            "get": {
                "description": "根据参数计算费用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "费用计算"
                ],
                "summary": "计算费用.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "需要速冲的数量",
                        "name": "energy",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "私钥",
                        "name": "privateKey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "0(宽带),1(能量)",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/justlend.FeeRatioRL"
                        }
                    }
                }
            }
        },
        "/rent": {
            "post": {
                "description": "租用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "交易"
                ],
                "summary": "租用.",
                "parameters": [
                    {
                        "description": "速冲地址",
                        "name": "receive",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "速冲类型0(宽带),1(能量)",
                        "name": "type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "速冲数量",
                        "name": "amount",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "扣费私钥",
                        "name": "privateKey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/justlend.RentResourceRL"
                        }
                    }
                }
            }
        },
        "/return": {
            "post": {
                "description": "退款",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "交易"
                ],
                "summary": "退款.",
                "parameters": [
                    {
                        "description": "速冲地址",
                        "name": "receive",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "速冲类型0(宽带),1(能量)",
                        "name": "type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "退款数量",
                        "name": "stakePerTrx",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "扣费私钥",
                        "name": "privateKey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/justlend.ReturnResourceRL"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "justlend.FeeRatioRL": {
            "type": "object",
            "properties": {
                "curFeeRatio": {
                    "type": "number"
                },
                "feeRatio": {
                    "type": "number"
                },
                "liquidateThreshold": {
                    "type": "number"
                },
                "minFee": {
                    "type": "number"
                },
                "prePayFee": {
                    "type": "number"
                },
                "rentAmount": {
                    "type": "integer"
                },
                "rentFee": {
                    "type": "number"
                },
                "rentalRate": {
                    "type": "number"
                },
                "stakePerTrx": {
                    "type": "integer"
                }
            }
        },
        "justlend.RentResourceRL": {
            "type": "object",
            "properties": {
                "stakePerTrx": {
                    "type": "integer"
                },
                "txId": {
                    "type": "string"
                }
            }
        },
        "justlend.ReturnResourceRL": {
            "type": "object",
            "properties": {
                "txId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "43.134.121.227:16688",
	BasePath:         "/v1",
	Schemes:          []string{"http"},
	Title:            "API接口文档",
	Description:      "提供 Justlend Energy RESTFUL API接口.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
